"""empty message

Revision ID: 3ea90ab0f208
Revises: 518022b5823f
Create Date: 2018-08-12 21:09:13.381446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea90ab0f208'
down_revision = '518022b5823f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'articles', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    # ### end Alembic commands ###
