"""empty message

Revision ID: 518022b5823f
Revises: 9f4c1f08d342
Create Date: 2018-08-10 17:20:25.299722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518022b5823f'
down_revision = '9f4c1f08d342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content_html', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'created')
    op.drop_column('articles', 'content_html')
    # ### end Alembic commands ###
