"""empty message

Revision ID: c7d06560fd7c
Revises: 3620440571b7
Create Date: 2018-08-16 18:53:56.946113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d06560fd7c'
down_revision = '3620440571b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'summary')
    # ### end Alembic commands ###
